# Generated by Django 3.1.6 on 2021-02-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('link', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('tags', models.JSONField()),
            ],
        ),
    ]
