# Generated by Django 3.1.6 on 2021-03-05 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(choices=[('EASY', 1), ('MEDIUM', 2), ('HARD', 3)])),
                ('name', models.CharField(max_length=100)),
                ('tags', models.JSONField()),
                ('url', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(0, 'CREATE'), (1, 'ATTEMPT')])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.IntegerField(choices=[(0, 'SOLVED_OPTIMALLY_IN_UNDER_25'), (1, 'SOLVED_SUBOPTIMALLY_IN_UNDER_25'), (2, 'SOLVED_OPTIMALLY_SLOWER'), (3, 'SOLVED_SUBOPTIMALLY_SLOWER'), (4, 'SOLVED_OPTIMALLY_WITH_HINT'), (5, 'SOLVED_SUBOPTIMALLY_WITH_HINT'), (6, 'NO_IDEA'), (7, 'NEVER_TRIED')])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='problem.problem')),
            ],
        ),
    ]
