# Generated by Django 3.1.6 on 2021-03-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'EASY'), (2, 'MEDIUM'), (3, 'HARD')]),
        ),
    ]
