# Generated by Django 3.1.6 on 2021-02-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='link',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
