# Generated by Django 3.1.6 on 2021-04-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlog',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
