# Generated by Django 3.1.6 on 2021-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problemlog_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlog',
            name='tags',
            field=models.ManyToManyField(related_name='problem_logs', to='problem.Tag'),
        ),
    ]
