# Generated by Django 3.1.6 on 2021-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20210306_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(related_name='problems', to='problem.Tag'),
        ),
    ]
