# Generated by Django 3.2 on 2021-06-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20210427_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='experience_target',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
