# Generated by Django 3.1.6 on 2021-03-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20210307_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
