# Generated by Django 3.1.6 on 2021-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20210308_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemlog',
            name='action',
        ),
    ]
